const Images = {
  twitter: require("../images/twitter.svg").default,
  facebook: require("../images/facebook.svg").default,
  instagram: require("../images/instagram.svg").default,
  sun: require("../images/sun.svg").default,
  moon: require("../images/moon.svg").default,
  focus: require("../images/focus.svg").default,
  easy: require("../images/easy.svg").default,
  industry: require("../images/industry.svg").default,
  close: require("../images/close.svg").default,
  Experience: require("../images/experience.svg").default,
  School: require("../images/school.svg").default,
  // Import Images here and svgs above
  laptop: require("../images/mockup.png"),
  smile: require("../images/pic1.png"),
  YouFirst: require("../images/pic2.png"),
  CameraLens: require("../images/pic3.png"),
  ariga: require("../images/ariga.png"),
  mobnia: require("../images/mobnia.png"),
  fundall: require("../images/fundall.png"),
  flutterwave: require("../images/flutter.png"),
  techpoint: require("../images/techpoint.png"),
  support: require("../images/support.png"),
  Group: require("../images/together.jpg"),
  Grid: require("../images/grid.png"),
  star1: require("../images/star1.png"),
  woods: require("../images/woods.jpg"),

  universe: require("../images/everywhere.png"),
  custom: require("../images/custom.png"),
};
export default Images;
